/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.peterfarlow.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":core"))
    implementation("com.github.ajalt.clikt:clikt:3.2.0")
}

application {
    // Define the main class for the application.
    mainClass.set("com.peterfarlow.app.AppKt")
}
