/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.peterfarlow.app

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import kotlinx.serialization.json.Json

class App : CliktCommand() {

    companion object {
        val serializer = Json { prettyPrint = true }
    }

    override fun run() = Unit
}

fun main(args: Array<String>) = App().subcommands(CreatePlayers(), CreateBirds()).main(args)
