/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.peterfarlow.app

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.IncorrectOptionValueCount
import com.github.ajalt.clikt.core.UsageError
import com.github.ajalt.clikt.parameters.options.multiple
import com.github.ajalt.clikt.parameters.options.option

class App : CliktCommand() {

    val players: List<String> by option().multiple(
        default = listOf("T.J.", "Alex", "Peter"),
    )

    override fun run() {
        validatePlayers()
        startGame()
    }

    private fun validatePlayers() {
        if (players.size <= 1) {
            throw UsageError("Must supply between two and six players")
        } else {
            echo("You entered ${players.size} players:")
            players.forEach { echo(it) }
        }
    }

    private fun startGame() {

    }
}

fun main(args: Array<String>) = App().main(args)
